# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend build&test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: measurements_frontend/measurement/package-lock.json
        
    - run: npm ci
      working-directory: measurements_frontend/measurement
    - run: npm run build --if-present
      working-directory: measurements_frontend/measurement
    - run: npm test
      working-directory: measurements_frontend/measurement
